[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.yaml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

